### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by johnthagen** [chtd/psycopg2cffi#114]
Last release was almost 2 years ago, but there have been many updates to master since then, most notably official Python 3.8 support: https://github.com/chtd/psycopg2cffi/commits/master

Could another release be pushed to PyPI?

**Comment by johnthagen** [comment]
Pinging @lopuhin to see if this can happen.

**Comment by jcpunk** [comment]
I'd also love to see a new version (and one with Wheels!)

**Comment by lopuhin** [comment]
I'll prepare a new release with https://github.com/chtd/psycopg2cffi/pull/121 and https://github.com/chtd/psycopg2cffi/pull/123 soon (everything else is released) - but without wheels, that's a separate feature.
If someone is willing to work on that + move tests to github actions, will be happy to review.

**Comment by johnthagen** [comment]
2.9.0 was released after this issue was opened, so closing:

- https://pypi.org/project/psycopg2cffi/2.9.0/
