### ISSUE TITLE
Adapting a DateRange object created with a unicode bounds fails.

### ISSUE THREAD

**Issue by schinckel** [chtd/psycopg2cffi#25]
In the process of making my code python3 compliant, I turned on unicode literals at the top of a test file:

    from __future__ import unicode_literals

Then, when attempting to adapt a DateRange object (but not a Numeric Range) object that I was creating manually, resulted in an error. The line of code that was run:

    DjangoFieldsModel.objects.filter(date__in=DateRange(lower='2001-01-01', upper='2001-01-03', bounds='(]'))

I believe it is because of the line:

https://github.com/chtd/psycopg2cffi/blob/master/psycopg2cffi/_range.py#L218

This line uses string formatting to inject the bounds, which, when they are a unicode object, results in that object becoming a unicode object.

This then results in the actual error:

      File "/Users/matt/Development/django-postgres/.tox/pypy/site-packages/psycopg2cffi/_impl/cursor.py", line 687, in _pq_execute
        self._pgres = libpq.PQexec(pgconn, query)
    TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

**Comment by lopuhin** [comment]
Than you for checking. Merged finally, py3, closing this issue.
