### ISSUE TITLE
Blog post not reachable anymore

### ISSUE THREAD

**Issue by mkesper** [chtd/psycopg2cffi#30]
Your blog post http://chtd.ru/blog/bystraya-rabota-s-postgres-pod-pypy/ seems not reachable at this time, sadly.

**Comment by lopuhin** [comment]
Uh, this looks like a problem with our site, thank you for reporting!

**Comment by lopuhin** [comment]
fixed the link, en verion is at http://chtd.ru/blog/bystraya-rabota-s-postgres-pod-pypy/?lang=en
