### ISSUE TITLE
Wrong handling of postgresqls bigint

### ISSUE THREAD

**Issue by pajowu** [chtd/psycopg2cffi#31]
If I use bigint, psycopg2cffi only uses unsigned int32. Large numbers become 2147483647.

**Comment by lopuhin** [comment]
Perhaps you can show some code that triggers it? I am just not quite sure which part or API is it - does it happen when reading bigint field from the database?

**Comment by pajowu** [comment]
Yes. I read large numbers ("5374144891846073" as an example in the databse), but I only get 2147483647 in the row via cursor.fetchone()

**Comment by lopuhin** [comment]
I need more info to reproduce - see b6d2dd4b - this test passes for me.

**Comment by lopuhin** [comment]
Ah, maybe it will fail on 32-bit

**Comment by lopuhin** [comment]
Should be fixed now (not uploaded to pypi yet), but could you give more information about your platform?

**Comment by pajowu** [comment]
32-Bit Arch Linux 3.17.6-1-ARCH Kernel with Pypy

**Comment by lopuhin** [comment]
Oh, that explains it. That was a really bad regression, thank you for reporting.

Uploaded to pypi
