### ISSUE TITLE
JSONB support?

### ISSUE THREAD

**Issue by rouge8** [chtd/psycopg2cffi#36]
Does psycopg2cffi have JSONB support? [Psycopg2 added it in 2.5.4](http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-5-5), but I'm not sure how the versions correspond.

**Comment by lopuhin** [comment]
No, there is no JSONB support in psycopg2cffi at the moment. I think this is the most important missing feature. I will be glad if you are willing to contribute it, or I will do it some day, maybe in the first half of May.

**Comment by rouge8** [comment]
That's what I thought. Is there a general comparison to what's available in
psycopg2?

**Comment by lopuhin** [comment]
Feature-wise current release is on par with psycopg2 2.5 (thanks to Daniele Varrazzo https://github.com/chtd/psycopg2cffi/pull/10), and has no extra features beyond that.

**Comment by tebanep** [comment]
Any ETA for this? I think this is a great feature that can put python on par with "modern" web stacks: nodejs + mongodb ~ pypy3.3 + tornado(asyncio) + postgresql(jsonb).

Thanks for this awesome work!

**Comment by lopuhin** [comment]
Thank you! I think some time this summe, maybe june or july.

**Comment by pmarti** [comment]
:+1: please support jsonb

**Comment by Natim** [comment]
We are pending on this issue in order to add PyPy support for Cliquet and Kinto. (https://github.com/mozilla-services/cliquet/issues/325)

**Comment by lopuhin** [comment]
Cool :)
I hope I will start this weekend, and will have a better estimate, and maybe something working.

**Comment by Natim** [comment]
Feel free to ask if you need help out can point us to something we can do to help.

**Comment by lopuhin** [comment]
Thank you for the support! In theory, it should be easy - just registering a new type, serialization/deserialization, and porting (mostly copying) tests from psycopg2. Moreover, there is psycopg2 code that already implements this feature. So, I hope there will be something to test soon.

**Comment by Natim** [comment]
Great thanks a lot :+1:

**Comment by lopuhin** [comment]
It turned out that psycopg2 implementation of jsonb support could be reused as-is, so I just merged jsonb support to master - tests pass, I'm going to run django 1.9 tests too to be sure. @Natim this is not on pypi yet, but if you can test on you side, this would be great! If all is well, I will put release to pypi on the weekend.

**Comment by brouberol** [comment]
On behalf of @Natim, I can tell you that our tests pass thanks to your merge. Thanks!

**Comment by Natim** [comment]
This is really great !!! Thanks a lot !

**Comment by lopuhin** [comment]
Great, thank you! Django 1.9 jsonb tests also pass, will release later today.

**Comment by lopuhin** [comment]
Release 2.7.1 to pypi

**Comment by brouberol** [comment]
Thanks again for being so reactive.

--
B
 
 
On Sat, Jun 20, 2015, at 11:07 AM, Konstantin Lopuhin wrote:
> Release 2.7.1 to pypi


> —
> Reply to this email directly or view it on GitHub[1]. 


>  


Links:

  1. https://github.com/chtd/psycopg2cffi/issues/36#issuecomment-113734440

**Comment by tebanep** [comment]
Great news, thanks a lot!
