### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by alex** [chtd/psycopg2cffi#7]
It would be awesome if psycopg2cffi had python 3 support.

(And if it does the .travis.yml should say so).

**Comment by thedrow** [comment]
Any news on this?

**Comment by b4stien** [comment]
I'd be highly interested in a py3k (and PyPy3) compatible release too: psycopg2cffi seems to be the only relevant driver for py2k, py3k, pypy and pypy3 support.

Is there any blocker still ?

**Comment by lopuhin** [comment]
Reviewed the diff, added pypy3 and py34 to tox.ini, merged and uploaded to pypi. Sorry for taking so long to finish it, especially after all the work was done.

**Comment by b4stien** [comment]
Thank you sir, great work!
